badge-for-build:
  description: badge for image build
  parameters:
    app:
      description: app name of badge
      type: string
      default: redmine-ecr-build-and-push
    color:
      description: color of badge
      type: string
      default: "#ffaa00"
    text:
      description: text of badge
      type: string
      default: success
  steps:
    - rj-package/create-badge:
        app: << parameters.app >>
        color: << parameters.color >>
        text: << parameters.text >>
        is_error_text: "failed"
    - rj-package/update-readme:
        fingerprint: << pipeline.parameters.rhems-redmine-finger-print >>

badge-for-apply-eks:
  parameters:
    app:
      description: app name of badge
      type: string
    color:
      description: color of badge
      type: string
      default: green
    text:
      description: text of badge
      type: string
      default: success
  steps:
    - rj-package/create-badge:
        app: << parameters.app >>
        color: << parameters.color >>
        text: << parameters.text >>
        is_error_text: "failed"
    - rj-package/update-readme:
        fingerprint: << pipeline.parameters.rhems-redmine-finger-print >>
