description: build and push to ecr
parameters:
  repo:
    type: string
    default: rhems-redmine
  component:
    type: string
    default: .
  tag:
    type: string
    # default: latest
    default: redmine-eks
steps:
  - checkout
  - aws-ecr/build-and-push-image:
      # aws-access-key-id: AWS_ACCESS_KEY_ID
      # aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      checkout: false
      remote-docker-layer-caching: true
      setup-remote-docker: true
      region: $AWS_DEFAULT_REGION
      repo: << parameters.repo >>
      path: << parameters.component >>
      tag: << parameters.tag >>