parameters:
  repo:
    type: string
    default: rhems-redmine
  component:
    type: string
    default: .
  tag:
    type: string
    # default: latest
    default: redmine-eks
steps:
  - checkout
  - aws-ecr/build-and-push-image:
      checkout: false
      remote-docker-layer-caching: true
      setup-remote-docker: true
      region: $AWS_DEFAULT_REGION
      repo: << parameters.repo >>
      path: << parameters.component >>
      tag: << parameters.tag >>

