aidis-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(aidis).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: aidis
          badge-app-name: redmine-aidis

bno-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(bno).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: bno
          badge-app-name: redmine-bno

ensky-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(ensky).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: ensky
          badge-app-name: redmine-ensky

liica-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(liica).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: liica
          badge-app-name: redmine-liica

mind-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(mind).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: mind
          badge-app-name: redmine-mind

pixyda-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(pixyda).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: pixyda
          badge-app-name: redmine-pixyda

rdl-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(rdl).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: rdl
          badge-app-name: redmine-rdl

rizap-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(rizap).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: rizap
          badge-app-name: redmine-rizap

rhems-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(rhems).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: rhems
          badge-app-name: redmine-rhems

diarkis-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(diarkis).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: diarkis
          badge-app-name: redmine-diarkis

survey-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(survey).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: survey
          badge-app-name: redmine-survey

drecom-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(drecom).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-prod:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-prod >>
          client-name: drecom
          badge-app-name: redmine-drecom
