### base-system
dev-karpenter-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "base-system-dev" ]
      - matches: { pattern: ".*(karpenter).*", value: << pipeline.parameters.apply-base >> }
  jobs:
    - karpenter-apply-develop:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-develop >>
          client-name: develop
          apply-target: karpenter
          badge-app-name: dev-karpenter

dev-storageclass-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "base-system-dev" ]
      - matches: { pattern: ".*(storageclass).*", value: << pipeline.parameters.apply-base >> }
  jobs:
    - karpenter-apply-develop:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-develop >>
          client-name: develop
          apply-target: storageclass
          badge-app-name: dev-storageclass

dev-admin-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "base-system-dev" ]
      - matches: { pattern: ".*{admin}.*", value: << pipeline.parameters.apply-base >> }
  jobs:
    - admin-apply-develop:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-develop >>
          client-name: develop
          apply-target: admin
          badge-app-name: dev-admin

### deployments
develop-apply:
  when:
    and:
      - equal: [ << pipeline.parameters.trigger >>, "redmine" ]
      - matches: { pattern: ".*(develop).*", value: << pipeline.parameters.clients >> }
  jobs:
    - eks-develop:
        executor:
          name: kubernetes-base
          cluster-name: << pipeline.parameters.eks-develop >>
          client-name: develop
          badge-app-name: redmine-develop
